apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  cephVersion:
    image: ceph/ceph:v14.2.4-20190917
    allowUnsupported: false
  dataDirHostPath: /var/lib/rook
  skipUpgradeChecks: false
  mon:
    count: 1
    allowMultiplePerNode: false
  mgr:
    modules:
    - name: pg_autoscalergr
      enabled: true
  dashboard:
    enabled: true
    port: 8080
    ssl: false
  monitoring:
    enabled: false
    rulesNamespace: rook-ceph
  network:
    hostNetwork: false
  rbdMirroring:
    workers: 0
  placement:
    all:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: pflaeging.net/rook-ceph-storage
              operator: In
              values:
              - "true"
  annotations:
  resources:
  removeOSDsIfOutAndSafeToRemove: false
  storage: # cluster level storage configuration and selection
      useAllNodes: true
      useAllDevices: false
      topologyAware: true
      deviceFilter:
      location:
      config:
        metadataDevice: "md0" # specify a non-rotational storage so ceph-volume will use it as block db device of bluestore.
        databaseSizeMB: "1024" # uncomment if the disks are smaller than 100 GB
        journalSizeMB: "1024"  # uncomment if the disks are 20 GB or smaller
        osdsPerDevice: "1" # this value can be overridden at the node or device level
        encryptedDevice: "false" # the default value for this option is "false"
      directories:
      - path: /data
      - path: /new
  disruptionManagement:
    managePodBudgets: false
    osdMaintenanceTimeout: 30
    manageMachineDisruptionBudgets: false
    machineDisruptionBudgetNamespace: openshift-machine-api
