apiVersion: authorization.openshift.io/v1
groupNames:
- system:authenticated:oauth
kind: ClusterRoleBinding
metadata:
  annotations:
    openshift.io/reconcile-protect: "false"
  name: self-provisioners
roleRef:
  name: self-provisioner
subjects:
- kind: SystemGroup
  name: system:authenticated:oauth
userNames: null
