apiVersion: v1
kind: Route
metadata:
  annotations:
    openshift.io/host.generated: "true"
  creationTimestamp: null
  labels:
    net.pflaeging.route: idptest-stickiebox-keycloak
  name: idptest-stickiebox-keycloak
spec:
  host: idptest.stickiebox.org
  port:
    targetPort: 8080-tcp
  tls:
    caCertificate: |
      -----BEGIN CERTIFICATE-----
      MIIGCDCCA/CgAwIBAgIQKy5u6tl1NmwUim7bo3yMBzANBgkqhkiG9w0BAQwFADCB
      hTELMAkGA1UEBhMCR0IxGzAZBgNVBAgTEkdyZWF0ZXIgTWFuY2hlc3RlcjEQMA4G
      A1UEBxMHU2FsZm9yZDEaMBgGA1UEChMRQ09NT0RPIENBIExpbWl0ZWQxKzApBgNV
      BAMTIkNPTU9ETyBSU0EgQ2VydGlmaWNhdGlvbiBBdXRob3JpdHkwHhcNMTQwMjEy
      MDAwMDAwWhcNMjkwMjExMjM1OTU5WjCBkDELMAkGA1UEBhMCR0IxGzAZBgNVBAgT
      EkdyZWF0ZXIgTWFuY2hlc3RlcjEQMA4GA1UEBxMHU2FsZm9yZDEaMBgGA1UEChMR
      Q09NT0RPIENBIExpbWl0ZWQxNjA0BgNVBAMTLUNPTU9ETyBSU0EgRG9tYWluIFZh
      bGlkYXRpb24gU2VjdXJlIFNlcnZlciBDQTCCASIwDQYJKoZIhvcNAQEBBQADggEP
      ADCCAQoCggEBAI7CAhnhoFmk6zg1jSz9AdDTScBkxwtiBUUWOqigwAwCfx3M28Sh
      bXcDow+G+eMGnD4LgYqbSRutA776S9uMIO3Vzl5ljj4Nr0zCsLdFXlIvNN5IJGS0
      Qa4Al/e+Z96e0HqnU4A7fK31llVvl0cKfIWLIpeNs4TgllfQcBhglo/uLQeTnaG6
      ytHNe+nEKpooIZFNb5JPJaXyejXdJtxGpdCsWTWM/06RQ1A/WZMebFEh7lgUq/51
      UHg+TLAchhP6a5i84DuUHoVS3AOTJBhuyydRReZw3iVDpA3hSqXttn7IzW3uLh0n
      c13cRTCAquOyQQuvvUSH2rnlG51/ruWFgqUCAwEAAaOCAWUwggFhMB8GA1UdIwQY
      MBaAFLuvfgI9+qbxPISOre44mOzZMjLUMB0GA1UdDgQWBBSQr2o6lFoL2JDqElZz
      30O0Oija5zAOBgNVHQ8BAf8EBAMCAYYwEgYDVR0TAQH/BAgwBgEB/wIBADAdBgNV
      HSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwGwYDVR0gBBQwEjAGBgRVHSAAMAgG
      BmeBDAECATBMBgNVHR8ERTBDMEGgP6A9hjtodHRwOi8vY3JsLmNvbW9kb2NhLmNv
      bS9DT01PRE9SU0FDZXJ0aWZpY2F0aW9uQXV0aG9yaXR5LmNybDBxBggrBgEFBQcB
      AQRlMGMwOwYIKwYBBQUHMAKGL2h0dHA6Ly9jcnQuY29tb2RvY2EuY29tL0NPTU9E
      T1JTQUFkZFRydXN0Q0EuY3J0MCQGCCsGAQUFBzABhhhodHRwOi8vb2NzcC5jb21v
      ZG9jYS5jb20wDQYJKoZIhvcNAQEMBQADggIBAE4rdk+SHGI2ibp3wScF9BzWRJ2p
      mj6q1WZmAT7qSeaiNbz69t2Vjpk1mA42GHWx3d1Qcnyu3HeIzg/3kCDKo2cuH1Z/
      e+FE6kKVxF0NAVBGFfKBiVlsit2M8RKhjTpCipj4SzR7JzsItG8kO3KdY3RYPBps
      P0/HEZrIqPW1N+8QRcZs2eBelSaz662jue5/DJpmNXMyYE7l3YphLG5SEXdoltMY
      dVEVABt0iN3hxzgEQyjpFv3ZBdRdRydg1vs4O2xyopT4Qhrf7W8GjEXCBgCq5Ojc
      2bXhc3js9iPc0d1sjhqPpepUfJa3w/5Vjo1JXvxku88+vZbrac2/4EjxYoIQ5QxG
      V/Iz2tDIY+3GH5QFlkoakdH368+PUq4NCNk+qKBR6cGHdNXJ93SrLlP7u3r7l+L4
      HyaPs9Kg4DdbKDsx5Q5XLVq4rXmsXiBmGqW5prU5wfWYQ//u+aen/e7KJD2AFsQX
      j4rBYKEMrltDR5FL1ZoXX/nUh8HCjLfn4g8wGTeGrODcQgPmlKidrv0PJFGUzpII
      0fxQ8ANAe4hZ7Q7drNJ3gjTcBpUC2JD5Leo31Rpg0Gcg19hCC0Wvgmje3WYkN5Ap
      lBlGGSW4gNfL1IYoakRwJiNiqZ+Gb7+6kHDSVneFeO/qJakXzlByjAA6quPbYzSf
      +AZxAeKCINT+b72x
      -----END CERTIFICATE-----
      -----BEGIN CERTIFICATE-----
      MIIFdDCCBFygAwIBAgIQJ2buVutJ846r13Ci/ITeIjANBgkqhkiG9w0BAQwFADBv
      MQswCQYDVQQGEwJTRTEUMBIGA1UEChMLQWRkVHJ1c3QgQUIxJjAkBgNVBAsTHUFk
      ZFRydXN0IEV4dGVybmFsIFRUUCBOZXR3b3JrMSIwIAYDVQQDExlBZGRUcnVzdCBF
      eHRlcm5hbCBDQSBSb290MB4XDTAwMDUzMDEwNDgzOFoXDTIwMDUzMDEwNDgzOFow
      gYUxCzAJBgNVBAYTAkdCMRswGQYDVQQIExJHcmVhdGVyIE1hbmNoZXN0ZXIxEDAO
      BgNVBAcTB1NhbGZvcmQxGjAYBgNVBAoTEUNPTU9ETyBDQSBMaW1pdGVkMSswKQYD
      VQQDEyJDT01PRE8gUlNBIENlcnRpZmljYXRpb24gQXV0aG9yaXR5MIICIjANBgkq
      hkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAkehUktIKVrGsDSTdxc9EZ3SZKzejfSNw
      AHG8U9/E+ioSj0t/EFa9n3Byt2F/yUsPF6c947AEYe7/EZfH9IY+Cvo+XPmT5jR6
      2RRr55yzhaCCenavcZDX7P0N+pxs+t+wgvQUfvm+xKYvT3+Zf7X8Z0NyvQwA1onr
      ayzT7Y+YHBSrfuXjbvzYqOSSJNpDa2K4Vf3qwbxstovzDo2a5JtsaZn4eEgwRdWt
      4Q08RWD8MpZRJ7xnw8outmvqRsfHIKCxH2XeSAi6pE6p8oNGN4Tr6MyBSENnTnIq
      m1y9TBsoilwie7SrmNnu4FGDwwlGTm0+mfqVF9p8M1dBPI1R7Qu2XK8sYxrfV8g/
      vOldxJuvRZnio1oktLqpVj3Pb6r/SVi+8Kj/9Lit6Tf7urj0Czr56ENCHonYhMsT
      8dm74YlguIwoVqwUHZwK53Hrzw7dPamWoUi9PPevtQ0iTMARgexWO/bTouJbt7IE
      IlKVgJNp6I5MZfGRAy1wdALqi2cVKWlSArvX31BqVUa/oKMoYX9w0MOiqiwhqkfO
      KJwGRXa/ghgntNWutMtQ5mv0TIZxMOmm3xaG4Nj/QN370EKIf6MzOi5cHkERgWPO
      GHFrK+ymircxXDpqR+DDeVnWIBqv8mqYqnK8V0rSS527EPywTEHl7R09XiidnMy/
      s1Hap0flhFMCAwEAAaOB9DCB8TAfBgNVHSMEGDAWgBStvZh6NLQm9/rEJlTvA73g
      JMtUGjAdBgNVHQ4EFgQUu69+Aj36pvE8hI6t7jiY7NkyMtQwDgYDVR0PAQH/BAQD
      AgGGMA8GA1UdEwEB/wQFMAMBAf8wEQYDVR0gBAowCDAGBgRVHSAAMEQGA1UdHwQ9
      MDswOaA3oDWGM2h0dHA6Ly9jcmwudXNlcnRydXN0LmNvbS9BZGRUcnVzdEV4dGVy
      bmFsQ0FSb290LmNybDA1BggrBgEFBQcBAQQpMCcwJQYIKwYBBQUHMAGGGWh0dHA6
      Ly9vY3NwLnVzZXJ0cnVzdC5jb20wDQYJKoZIhvcNAQEMBQADggEBAGS/g/FfmoXQ
      zbihKVcN6Fr30ek+8nYEbvFScLsePP9NDXRqzIGCJdPDoCpdTPW6i6FtxFQJdcfj
      Jw5dhHk3QBN39bSsHNA7qxcS1u80GH4r6XnTq1dFDK8o+tDb5VCViLvfhVdpfZLY
      Uspzgb8c8+a4bmYRBbMelC1/kZWSWfFMzqORcUx8Rww7Cxn2obFshj5cqsQugsv5
      B5a6SE2Q8pTIqXOi6wZ7I53eovNNVZ96YUWYGGjHXkBrI/V5eu+MtWuLt29G9Hvx
      PUsE2JOAWVrgQSQdso8VYFhH2+9uRv0V9dlfmrPb2LjkQLPNlzmuhbsdjrzch5vR
      pu/xO28QOG8=
      -----END CERTIFICATE-----
      -----BEGIN CERTIFICATE-----
      MIIENjCCAx6gAwIBAgIBATANBgkqhkiG9w0BAQUFADBvMQswCQYDVQQGEwJTRTEU
      MBIGA1UEChMLQWRkVHJ1c3QgQUIxJjAkBgNVBAsTHUFkZFRydXN0IEV4dGVybmFs
      IFRUUCBOZXR3b3JrMSIwIAYDVQQDExlBZGRUcnVzdCBFeHRlcm5hbCBDQSBSb290
      MB4XDTAwMDUzMDEwNDgzOFoXDTIwMDUzMDEwNDgzOFowbzELMAkGA1UEBhMCU0Ux
      FDASBgNVBAoTC0FkZFRydXN0IEFCMSYwJAYDVQQLEx1BZGRUcnVzdCBFeHRlcm5h
      bCBUVFAgTmV0d29yazEiMCAGA1UEAxMZQWRkVHJ1c3QgRXh0ZXJuYWwgQ0EgUm9v
      dDCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBALf3GjPm8gAELTngTlvt
      H7xsD821+iO2zt6bETOXpClMfZOfvUq8k+0DGuOPz+VtUFrWlymUWoCwSXrbLpX9
      uMq/NzgtHj6RQa1wVsfwTz/oMp50ysiQVOnGXw94nZpAPA6sYapeFI+eh6FqUNzX
      mk6vBbOmcZSccbNQYArHE504B4YCqOmoaSYYkKtMsE8jqzpPhNjfzp/haW+710LX
      a0Tkx63ubUFfclpxCDezeWWkWaCUN/cALw3CknLa0Dhy2xSoRcRdKn23tNbE7qzN
      E0S3ySvdQwAl+mG5aWpYIxG3pzOPVnVZ9c0p10a3CitlttNCbxWyuHv77+ldU9U0
      WicCAwEAAaOB3DCB2TAdBgNVHQ4EFgQUrb2YejS0Jvf6xCZU7wO94CTLVBowCwYD
      VR0PBAQDAgEGMA8GA1UdEwEB/wQFMAMBAf8wgZkGA1UdIwSBkTCBjoAUrb2YejS0
      Jvf6xCZU7wO94CTLVBqhc6RxMG8xCzAJBgNVBAYTAlNFMRQwEgYDVQQKEwtBZGRU
      cnVzdCBBQjEmMCQGA1UECxMdQWRkVHJ1c3QgRXh0ZXJuYWwgVFRQIE5ldHdvcmsx
      IjAgBgNVBAMTGUFkZFRydXN0IEV4dGVybmFsIENBIFJvb3SCAQEwDQYJKoZIhvcN
      AQEFBQADggEBALCb4IUlwtYj4g+WBpKdQZic2YR5gdkeWxQHIzZlj7DYd7usQWxH
      YINRsPkyPef89iYTx4AWpb9a/IfPeHmJIZriTAcKhjW88t5RxNKWt9x+Tu5w/Rw5
      6wwCURQtjr0W4MHfRnXnJK3s9EK0hZNwEGe6nQY1ShjTK3rMUUKhemPR5ruhxSvC
      Nr4TDea9Y355e6cJDUCrat2PisP29owaQgVR1EX1n6diIWgVIEM8med8vSTYqZEX
      c4g/VhsxOBi0cQ+azcgOno4uG+GMmIPLHzHxREzGBHNJdmAPx/i9F4BrLunMTA5a
      mnkPIAou1Z5jJh5VkpTYghdae9C8x49OhgQ=
      -----END CERTIFICATE-----
    certificate: |
      -----BEGIN CERTIFICATE-----
      MIIG2zCCBcOgAwIBAgIQWqLRaUBUp7p2+y86GBAplDANBgkqhkiG9w0BAQsFADCB
      kDELMAkGA1UEBhMCR0IxGzAZBgNVBAgTEkdyZWF0ZXIgTWFuY2hlc3RlcjEQMA4G
      A1UEBxMHU2FsZm9yZDEaMBgGA1UEChMRQ09NT0RPIENBIExpbWl0ZWQxNjA0BgNV
      BAMTLUNPTU9ETyBSU0EgRG9tYWluIFZhbGlkYXRpb24gU2VjdXJlIFNlcnZlciBD
      QTAeFw0xODA4MDYwMDAwMDBaFw0yMDA4MDUyMzU5NTlaMF0xITAfBgNVBAsTGERv
      bWFpbiBDb250cm9sIFZhbGlkYXRlZDEdMBsGA1UECxMUUG9zaXRpdmVTU0wgV2ls
      ZGNhcmQxGTAXBgNVBAMMECouc3RpY2tpZWJveC5vcmcwggEiMA0GCSqGSIb3DQEB
      AQUAA4IBDwAwggEKAoIBAQDrZc9PA50BoVlPSeOPCHisNUolcPiSwbin73Nm4wDb
      rsFcreBukThrQ/TLUfxSrNoqvbuJEGbRG7mTnw6Q29sKkTm4/UsCEpNd0fIRuI1J
      tnlfnEoCZ7Dw4GaF9ongx1EB3/VBpvnzuku/3IyxpgOApLsw0BNhOepmkeC2expZ
      Sebw0fkKt94ZlSiPU5foDNxx8Ft8Cbgmj7LTiA90mLbLXbwEV4tsZSPXQktPDoPc
      12gi9VDtRIEojcJ5rRNAZDG6jP58cPIvS7FoeTUrJR/yyGD9PXpe6bnefb5thRmD
      /5zZXbqEktBZnusPgNcgHLXkC7yPE+r32YSQ+BL5pdFjAgMBAAGjggNhMIIDXTAf
      BgNVHSMEGDAWgBSQr2o6lFoL2JDqElZz30O0Oija5zAdBgNVHQ4EFgQUO/1socq6
      rco0QrO70sfMLQQgDt8wDgYDVR0PAQH/BAQDAgWgMAwGA1UdEwEB/wQCMAAwHQYD
      VR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCME8GA1UdIARIMEYwOgYLKwYBBAGy
      MQECAgcwKzApBggrBgEFBQcCARYdaHR0cHM6Ly9zZWN1cmUuY29tb2RvLmNvbS9D
      UFMwCAYGZ4EMAQIBMFQGA1UdHwRNMEswSaBHoEWGQ2h0dHA6Ly9jcmwuY29tb2Rv
      Y2EuY29tL0NPTU9ET1JTQURvbWFpblZhbGlkYXRpb25TZWN1cmVTZXJ2ZXJDQS5j
      cmwwgYUGCCsGAQUFBwEBBHkwdzBPBggrBgEFBQcwAoZDaHR0cDovL2NydC5jb21v
      ZG9jYS5jb20vQ09NT0RPUlNBRG9tYWluVmFsaWRhdGlvblNlY3VyZVNlcnZlckNB
      LmNydDAkBggrBgEFBQcwAYYYaHR0cDovL29jc3AuY29tb2RvY2EuY29tMCsGA1Ud
      EQQkMCKCECouc3RpY2tpZWJveC5vcmeCDnN0aWNraWVib3gub3JnMIIBgAYKKwYB
      BAHWeQIEAgSCAXAEggFsAWoAdwDuS723dc5guuFCaR+r4Z5mow9+X7By2IMAxHuJ
      eqj9ywAAAWUQemE1AAAEAwBIMEYCIQD2pq9NK8oJRRuI39enereOfYIrvs41+GH5
      gUzwu3CJ1QIhAIT0WYSfM1mG3D4gjfyiTJMDg276NEzCPH4yq+p4qOu9AHcAXqdz
      +d9WwOe1Nkh90EngMnqRmgyEoRIShBh1loFxRVgAAAFlEHpjOwAABAMASDBGAiEA
      1TAmzIVXv2z3XnDx3sw4UOZIP3qAjsKZkLyRy2GvMpgCIQCwixEhsceJayVVnJY2
      XUPNpQFV7hLjE+XALajLVztyAwB2AFWB1MIWkDYBSuoLm1c8U/DA5Dh4cCUIFy+j
      qh0HE9MMAAABZRB6YVkAAAQDAEcwRQIhAJfYhyIqL32NnnaHkxC7/VccaxFt4wGC
      WYWHx6qOU7sNAiByXPzBBQO8yw1qG1MSwvdGq9kaiuWxy2RjEKImKlgcLTANBgkq
      hkiG9w0BAQsFAAOCAQEAd/rMN/Rcsup2UxZgdgLbi2rob9SV+sxhpksl3fleGMRZ
      G4hZpaX6E7daOBmvuet5kZrfUV8MCkYFR6wtEJS58SNZV43j6J8nUO+u0L6yg8tN
      T/Ke3rhbmK8QsU7CTnLrnuQEF+WR9g3DYSkbn5DOubHOC2woHr6A2HiP7Px3okEI
      6/mnpNM+htQdAHrYGDXohbYCSXPEyEjlr0nfkcHog15fEIvbvsY5WDFFttG0b/OI
      nJVB8HwBga+VH7ON8DtpT5xIYCHgVERG3AiUX3nrBeuHmet/dfp4Y1ZqZRbqgwdk
      YVHHvkYPqM2eAOtiXI8LduYv8E3PhyRmWQDlSXqBIw==
      -----END CERTIFICATE-----
    key: |
      -----BEGIN RSA PRIVATE KEY-----
      MIIEowIBAAKCAQEA62XPTwOdAaFZT0njjwh4rDVKJXD4ksG4p+9zZuMA267BXK3g
      bpE4a0P0y1H8UqzaKr27iRBm0Ru5k58OkNvbCpE5uP1LAhKTXdHyEbiNSbZ5X5xK
      Amew8OBmhfaJ4MdRAd/1Qab587pLv9yMsaYDgKS7MNATYTnqZpHgtnsaWUnm8NH5
      CrfeGZUoj1OX6AzccfBbfAm4Jo+y04gPdJi2y128BFeLbGUj10JLTw6D3NdoIvVQ
      7USBKI3Cea0TQGQxuoz+fHDyL0uxaHk1KyUf8shg/T16Xum53n2+bYUZg/+c2V26
      hJLQWZ7rD4DXIBy15Au8jxPq99mEkPgS+aXRYwIDAQABAoIBAQDliheG8v0M8+sE
      uAZgGWCifCxbKjgZ0zFfAM3FTCIwFc6TszGgX5dmcZOpF782Vzs+ZlkSpJ291o01
      d+paMyj6uvZQfx2/XaG54Nltkkqj0H22T86TXc1adVdD1k5Ik9NYQq0DYfFmSwlG
      g6fmKv5LWVb3mE7the4eKq23A3+EA/+YEy5VAG08cdAqeQPjTi1xX0VyF0uvCz9N
      1N1ywGkhoccKvHDtK2C0mGhZg/HUiRmrDKXsGNWRGEASuk76ziAYw4TE4ruRYXuS
      utVKDgbhBzRjvjsxrMmhUltTxt4DZQf9xEwwHUVx/rCSpYtH1rrCvmot/PE+7W24
      p5AeEPqxAoGBAPgnU64Q1vv9JNfzbXw82/xDJopQesJVN/cB1uvjafaI9fWZVFDT
      At4c2XssCIr76ukVsyDpgppE41WSWyDKuMlBiHaINFcn6I68/EH5bS98ZlJclfqt
      DGQ56VnepSk2Qpm/uZw/lPGA8prupTGDmGxHoc9CDwb9Ao+TuFHQfZGnAoGBAPLX
      OvwA3JaGS0QZ+a3sGA9uEggoT4o7/+hDmkKdP7hseLWRNO9tIjgDGo7t6YJNco5v
      DIVWRo3YyVaQGC71xfanbGO1CrsC6ZfVRp01V7K+WjdIkggSS1bBjusNFVaESUja
      /OeitysdA099dSDuVTdMVudAF3T2GBDm5BzjlCHlAoGAOfeNz5J1dcWrbpqZj7Tz
      uljBTvv/wReBDD0sxEuKPCHAOs/HZ13zRIk+sEwX7sdsF2iPQHfrnzfKVvnqOZ3B
      Tpn1U6L7fwR+iaFR1+N5AuevSzv/eOAljeANR4X/1MGtCxdDN2GO3F8/zLtEcW2J
      FHojLTQEKKC/kWRzYQEv4+8CgYBg02amYmWR8xwBnGXMbi2twVKZRBFq6b+Ayaux
      Uee9TirXIn271YTmVn55bO1FUkIR/r88Twk0t7KXvD6YQtDbJyh1nRMZO/EN5DES
      r9k24OUx09K+OyUlA2pL2FygsYBS91YNufhUzW2rfTd9mOoLcXnZHNn9fb5cxuM/
      jZJb7QKBgFBYdOBYMkNJZmPWxlEzDpXISZyyatTaJDrqpRLEBjpdRWbR7h39ZqQD
      1Vk+kFo+21zHiXknOx5JYg47Q3TMVaqRvo4q7dlBl6cfICN3Ggg/jUMuUpxbcbmA
      AW+/FhTiK5L03r86H9R3Bsc+2+fiqr3ZSWh+PmJMunnhYXhNc74R
      -----END RSA PRIVATE KEY-----
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  to:
    kind: Service
    name: idptest-stickiebox-keycloak
    weight: 100
  wildcardPolicy: None
status: {}