apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    net.pflaeging.vc: postgresql
    net.pflaeging.instance: system-keycloak
  name: system-keycloak-pg-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  selector:
    matchLabels:
      net.pflaeging.instance: system-keycloak
      net.pflaeging.volumetype: postgresql
status: {}