apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    net.pflaeging.service: postgresql
    net.pflaeging.instance: system-keycloak
  name: system-keycloak-postgresql
spec:
  ports:
  - name: 5432-tcp
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    net.pflaeging.deployment: system-keycloak-postgresql
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}