kind: PersistentVolume
apiVersion: v1
metadata:
  name: system-keycloak-postgresql
  labels:
    net.pflaeging.instance: system-keycloak
    net.pflaeging.volumetype: postgresql
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: nfs1.pfpk.pro
    path: /exports/system-keycloak-postgresql.lothlorien.pfpk.pro